[package]
name = "mtag-deserializinator-inator"
version = "0.1.0"
edition = "2021"
authors = ["Gabriel Antoniak <gjantoni@umich.edu>"]

[dependencies]
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"